USE Iconoteca;

SELECT * FROM usuarios;
SELECT * FROM categorias;
SELECT * FROM artefatos;
SELECT * FROM imagens;

-- Usuarios
INSERT INTO users (nome, email, senha) VALUE ('admin', 'admin@gmail.com', '202cb962ac59075b964b07152d234b70');

-- Categorias
INSERT INTO categorias (nomeCategoria, nomeURL) VALUES ("Outro", "outro"), ("Lítico", "litico"), ("Cerâmica", "ceramica");

-- Artefatos
INSERT INTO artefatos (idOwner, nome, categoria, shortDesc, complDesc, nomeArquivo, lat, lng, figure) VALUES
(1, "Artefato 01_25", "ceramica",	"Descrição do portfólio do Artefato 01_25",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "01_25.stl",  -28.231451442049583, -52.381753658288574, "img1.jpg"),
(1, "Artefato 01_50", "litico", 	"Descrição do portfólio do Artefato 01_50",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "01_50.stl",  -28.231451442049583, -52.381753658288574, "img1.jpg"),
(1, "Artefato 01_75", "outro", 		"Descrição do portfólio do Artefato 01_75",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "01_75.stl",  -28.231451442049583, -52.381753658288574, "img1.jpg"),
(1, "Artefato 01_90", "ceramica", 	"Descrição do portfólio do Artefato 01_90",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "01_90.stl",  -28.231451442049583, -52.381753658288574, "img1.jpg"),
(1, "Artefato 01_100", "litico", 	"Descrição do portfólio do Artefato 01_100", "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "01_100.stl", -28.231451442049583, -52.381753658288574, "img1.jpg"),
(1, "Artefato 02_25", "outro", 		"Descrição do portfólio do Artefato 02_25",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "02_25.stl",  -28.231451442049583, -52.381753658288574, "img2.jpg"),
(1, "Artefato 02_50", "ceramica", 	"Descrição do portfólio do Artefato 02_50",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "02_50.stl",  -28.231451442049583, -52.381753658288574, "img2.jpg"),
(1, "Artefato 02_75", "litico", 	"Descrição do portfólio do Artefato 02_75",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "02_75.stl",  -28.231451442049583, -52.381753658288574, "img2.jpg"),
(1, "Artefato 02_90", "outro", 		"Descrição do portfólio do Artefato 02_90",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "02_90.stl",  -28.231451442049583, -52.381753658288574, "img2.jpg"),
(1, "Artefato 02_100", "ceramica", 	"Descrição do portfólio do Artefato 02_100", "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "02_100.stl", -28.231451442049583, -52.381753658288574, "img2.jpg"),
(1, "Artefato 03_50", "litico", 	"Descrição do portfólio do Artefato 03_50",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "03_50.stl",  -28.231451442049583, -52.381753658288574, "img3.jpg"),
(1, "Artefato 03_75", "outro",   	"Descrição do portfólio do Artefato 03_75",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "03_75.stl",  -28.231451442049583, -52.381753658288574, "img3.jpg"),
(1, "Artefato 03_90", "ceramica",	"Descrição do portfólio do Artefato 03_90",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "03_90.stl",  -28.231451442049583, -52.381753658288574, "img3.jpg"),
(1, "Artefato 03_100", "litico", 	"Descrição do portfólio do Artefato 03_100", "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "03_100.stl", -28.231451442049583, -52.381753658288574, "img3.jpg"),
(1, "Artefato 04_50", "outro", 		"Descrição do portfólio do Artefato 04_50",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "04_50.stl",  -28.231451442049583, -52.381753658288574, "img4.jpg"),
(1, "Artefato 04_75", "ceramica",	"Descrição do portfólio do Artefato 04_75",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "04_75.stl",  -28.231451442049583, -52.381753658288574, "img4.jpg"),
(1, "Artefato 04_90", "litico", 	"Descrição do portfólio do Artefato 04_90",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "04_90.stl",  -28.231451442049583, -52.381753658288574, "img4.jpg"),
(1, "Artefato 04_95", "outro", 		"Descrição do portfólio do Artefato 04_95",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "04_95.stl",  -28.231451442049583, -52.381753658288574, "img4.jpg"),
(1, "Artefato 04_100", "ceramica", 	"Descrição do portfólio do Artefato 04_100", "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "04_100.stl", -28.231451442049583, -52.381753658288574, "img4.jpg"),
(1, "Artefato 01_25", "litico", 	"Descrição do portfólio do Artefato 01_25",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "01_25.stl",  -28.231451442049583, -52.381753658288574, "img1.jpg"),
(1, "Artefato 01_50", "outro", 		"Descrição do portfólio do Artefato 01_50",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "01_50.stl",  -28.231451442049583, -52.381753658288574, "img1.jpg"),
(1, "Artefato 01_75", "ceramica", 	"Descrição do portfólio do Artefato 01_75",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "01_75.stl",  -28.231451442049583, -52.381753658288574, "img1.jpg"),
(1, "Artefato 01_90", "litico", 	"Descrição do portfólio do Artefato 01_90",  "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "01_90.stl",  -28.231451442049583, -52.381753658288574, "img1.jpg"),
(1, "Artefato 01_100", "outro",   	"Descrição do portfólio do Artefato 01_100", "<p style=\"text-align: justify;\">Lorem ipsum dolor sit amet, consectetur <strong>adipiscing elit</strong>. Maecenas eu nulla sagittis, dapibus massa vitae, pharetra tortor. Proin dignissim ipsum et ornare tempus. Aliquam erat volutpat. Praesent feugiat commodo lectus, ac interdum ligula vehicula id. Nunc suscipit, elit id aliquam efficitur, tellus quam sagittis lectus, sed aliquam nunc eros in ex. Ut eu dui ipsum. Nam sapien ligula, ultricies a gravida et, porta vel neque. <strong>Sed nibh eros, ultricies ut justo ut, rhoncus pulvinar ex</strong>. Quisque id erat ut est aliquet viverra non sed mi.</p>
<p style=\"text-align: justify;\">Vivamus ac odio at diam accumsan pulvinar. Phasellus sed arcu nunc. Proin a <em>elementum odio</em>, ut lacinia justo. Praesent pulvinar at leo non ornare. Sed id rhoncus lectus. In lacinia <strong>consectetur</strong> mauris at vulputate. Quisque finibus gravida nibh nec ornare.</p>
<p style=\"text-align: justify;\">Nam <strong>pellentesque</strong>, erat ut luctus facilisis, sem ligula rutrum orci, egestas <span style=\"text-decoration: line-through;\">varius tortor</span> mi ornare turpis. Vivamus sit amet ligula sed diam dignissim varius ut sit amet nisi. Quisque in ligula ultricies, ullamcorper magna nec, sagittis odio. Aliquam et dolor et diam euismod lobortis et vel est. Ut imperdiet, turpis eu <em>faucibus vehicula</em>, lacus nulla porttitor lacus, accumsan euismod magna quam at ante. Curabitur sit amet orci iaculis, gravida massa ut, viverra justo. Etiam quis nibh in tortor aliquet dapibus ultrices eget arcu. <strong>Duis porta ante nunc, sit amet feugiat nisi tincidunt quis</strong>. Fusce sit amet tincidunt nisi. Ut sodales diam ut felis varius sagittis. Vivamus dapibus ut mi ultrices condimentum. Sed sed lacinia quam. Nunc augue orci, euismod ut ipsum at, porttitor finibus velit. Pellentesque hendrerit ex accumsan, consequat ante at, egestas odio. Mauris aliquet posuere laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
<p style=\"text-align: justify;\">Aenean id imperdiet dolor. Vestibulum molestie tempor eros. Sed arcu nisl, consequat eu elit vel, porttitor viverra lacus. Praesent a ipsum tincidunt lectus finibus viverra eu<strong> vestibulum</strong> eros. Ut sit amet nunc eget est consequat vulputate. In sollicitudin massa ac ullamcorper finibus. In et eleifend mi. Sed convallis vulputate eleifend. Phasellus massa metus, rhoncus vel tellus id, pulvinar blandit ex. Integer at dapibus magna. Sed ullamcorper nunc hendrerit odio mollis porta.</p>
", "01_100.stl", -28.231451442049583, -52.381753658288574, "img1.jpg");

-- Imagens
INSERT INTO imagens (idIcone, nomeImagem) VALUES
(1,  "objeto01.jpg"), (1,  "objeto02.jpg"), (1,  "objeto03.jpg"), (1,  "objeto04.jpg"), (1,   "objeto01.jpg"), (1,   "objeto02.jpg"),
(2,  "objeto02.jpg"), (2,  "objeto03.jpg"), (2,  "objeto04.jpg"), (2,  "objeto01.jpg"), (2,   "objeto02.jpg"), (2,   "objeto03.jpg"),
(3,  "objeto03.jpg"), (3,  "objeto04.jpg"), (3,  "objeto01.jpg"), (3,  "objeto02.jpg"), (3,   "objeto03.jpg"), (3,   "objeto04.jpg"),
(4,  "objeto04.jpg"), (4,  "objeto01.jpg"), (4,  "objeto02.jpg"), (4,  "objeto03.jpg"), (4,   "objeto04.jpg"), (4,   "objeto01.jpg"),
(5,  "objeto01.jpg"), (5,  "objeto02.jpg"), (5,  "objeto03.jpg"), (5,  "objeto04.jpg"), (5,   "objeto01.jpg"), (5,   "objeto02.jpg"),
(6,  "objeto02.jpg"), (6,  "objeto03.jpg"), (6,  "objeto04.jpg"), (6,  "objeto01.jpg"), (6,   "objeto02.jpg"), (6,   "objeto03.jpg"),
(7,  "objeto03.jpg"), (7,  "objeto04.jpg"), (7,  "objeto01.jpg"), (7,  "objeto02.jpg"), (7,   "objeto03.jpg"), (7,   "objeto04.jpg"),
(8,  "objeto04.jpg"), (8,  "objeto01.jpg"), (8,  "objeto02.jpg"), (8,  "objeto03.jpg"), (8,   "objeto04.jpg"), (8,   "objeto01.jpg"),
(9,  "objeto01.jpg"), (9,  "objeto02.jpg"), (9,  "objeto03.jpg"), (9,  "objeto04.jpg"), (9,   "objeto01.jpg"), (9,   "objeto02.jpg"),
(10, "objeto02.jpg"), (10, "objeto03.jpg"), (10, "objeto04.jpg"), (10, "objeto01.jpg"), (10,  "objeto02.jpg"), (10,  "objeto03.jpg"),
(11, "objeto03.jpg"), (11, "objeto04.jpg"), (11, "objeto01.jpg"), (11, "objeto02.jpg"), (11,  "objeto03.jpg"), (11,  "objeto04.jpg"),
(12, "objeto04.jpg"), (12, "objeto01.jpg"), (12, "objeto02.jpg"), (12, "objeto03.jpg"), (12,  "objeto04.jpg"), (12,  "objeto01.jpg"),
(13, "objeto01.jpg"), (13, "objeto02.jpg"), (13, "objeto03.jpg"), (13, "objeto04.jpg"), (13,  "objeto01.jpg"), (13,  "objeto02.jpg"),
(14, "objeto02.jpg"), (14, "objeto03.jpg"), (14, "objeto04.jpg"), (14, "objeto01.jpg"), (14,  "objeto02.jpg"), (14,  "objeto03.jpg"),
(15, "objeto03.jpg"), (15, "objeto04.jpg"), (15, "objeto01.jpg"), (15, "objeto02.jpg"), (15,  "objeto03.jpg"), (15,  "objeto04.jpg"),
(16, "objeto04.jpg"), (16, "objeto01.jpg"), (16, "objeto02.jpg"), (16, "objeto03.jpg"), (16,  "objeto04.jpg"), (16,  "objeto01.jpg"),
(17, "objeto01.jpg"), (17, "objeto02.jpg"), (17, "objeto03.jpg"), (17, "objeto04.jpg"), (17,  "objeto01.jpg"), (17,  "objeto02.jpg"),
(18, "objeto02.jpg"), (18, "objeto03.jpg"), (18, "objeto04.jpg"), (18, "objeto01.jpg"), (18,  "objeto02.jpg"), (18,  "objeto03.jpg"),
(19, "objeto03.jpg"), (19, "objeto04.jpg"), (19, "objeto01.jpg"), (19, "objeto02.jpg"), (19,  "objeto03.jpg"), (19,  "objeto04.jpg"),
(20, "objeto04.jpg"), (20, "objeto01.jpg"), (20, "objeto02.jpg"), (20, "objeto03.jpg"), (20,  "objeto04.jpg"), (20,  "objeto01.jpg"),
(21, "objeto01.jpg"), (21, "objeto02.jpg"), (21, "objeto03.jpg"), (21, "objeto04.jpg"), (21,  "objeto01.jpg"), (21,  "objeto02.jpg"),
(22, "objeto02.jpg"), (22, "objeto03.jpg"), (22, "objeto04.jpg"), (22, "objeto01.jpg"), (22,  "objeto02.jpg"), (22,  "objeto03.jpg"),
(23, "objeto03.jpg"), (23, "objeto04.jpg"), (23, "objeto01.jpg"), (23, "objeto02.jpg"), (23,  "objeto03.jpg"), (23,  "objeto04.jpg"),
(24, "objeto04.jpg"), (24, "objeto01.jpg"), (24, "objeto02.jpg"), (24, "objeto03.jpg"), (24,  "objeto04.jpg"), (24,  "objeto01.jpg");